/**
 * @author Louis Figes
 * @generated This function was generated by GitHub Copilot.
 */
function getYouTubeID(url) {
    let videoId = url.split('v=')[1];
    const ampersandPosition = videoId.indexOf('&');
    if(ampersandPosition !== -1) {
        videoId = videoId.substring(0, ampersandPosition);
    }
    return videoId;
}

export default getYouTubeID;